version: '2'
services:
  llvm:
    build: .
    volumes:
      - ./src:/var/llvm
      - ./obj:/var/Debug+Asserts
    command: ['/bin/bash']
    environment:
      OBJ_ROOT: '/var/Debug+Asserts'
      SRC_ROOT: '/var/llvm'
